import { useState, useEffect } from "react";
import C from "../lib/colors.js";
import { useVoice } from "../hooks/useVoice.js";
import { Card, Btn } from "./ui.jsx";
import { CONDITIONS } from "../data/conditions.js";
import { callClaude } from "../lib/api.js";

function printDoctorSummary({ user, conditions, result }) {
  const now = new Date().toLocaleDateString("en-AU", {
    day: "numeric", month: "long", year: "numeric",
  });

  const rows = conditions.map((name) => {
    const c = CONDITIONS[name];
    if (!c) return "";
    return `
      <div class="condition-block">
        <h3>${name}</h3>
        <p class="cause"><strong>True Cause (per Anthony William):</strong> ${c.cause}</p>
        <table>
          <tr>
            <td class="col-head">Recommended Supplements</td>
            <td class="col-head">Foods to Avoid</td>
          </tr>
          <tr>
            <td><ul>${c.supps.map((s) => `<li>${s}</li>`).join("")}</ul></td>
            <td><ul>${c.avoid.map((a) => `<li>${a}</li>`).join("")}</ul></td>
          </tr>
        </table>
        ${c.book ? `<p class="book-ref">📚 Reference: <em>${c.book}</em> by Anthony William</p>` : ""}
      </div>`;
  }).join("");

  const aiSection = result ? `
    <div class="ai-section">
      <h2>AI-Generated Healing Protocol</h2>
      <p class="ai-note">The following was generated by the CelerySync AI Guide based on Anthony William's Medical Medium teachings:</p>
      <div class="ai-body">${result.replace(/\n/g, "<br>")}</div>
    </div>` : "";

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>CelerySync — Healing Protocol for ${user?.name || "Patient"}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: Georgia, serif; color: #1a1a1a; padding: 36px; max-width: 780px; margin: 0 auto; }
    header { border-bottom: 2px solid #6b8f71; padding-bottom: 16px; margin-bottom: 24px; display: flex; justify-content: space-between; align-items: flex-end; }
    header h1 { font-size: 22px; color: #3d5e42; }
    header .meta { font-size: 12px; color: #555; text-align: right; line-height: 1.6; }
    .patient-box { background: #f5f9f5; border: 1px solid #c8deca; border-radius: 8px; padding: 14px 18px; margin-bottom: 22px; font-size: 13px; }
    .patient-box h2 { font-size: 14px; color: #3d5e42; margin-bottom: 8px; }
    .patient-box p { line-height: 2; }
    .condition-block { margin-bottom: 28px; padding-bottom: 20px; border-bottom: 1px solid #e0e8e0; }
    .condition-block h3 { font-size: 17px; color: #3d5e42; margin-bottom: 8px; }
    .cause { font-size: 12.5px; color: #444; line-height: 1.6; margin-bottom: 10px; }
    table { width: 100%; border-collapse: collapse; font-size: 12px; }
    .col-head { background: #e8f0e8; font-weight: 700; padding: 7px 10px; font-size: 12px; color: #3d5e42; }
    td { padding: 6px 10px; vertical-align: top; border: 1px solid #dde8dd; }
    ul { padding-left: 16px; }
    li { margin-bottom: 3px; line-height: 1.5; }
    .book-ref { font-size: 11.5px; color: #6b7280; margin-top: 8px; font-style: italic; }
    .ai-section { margin-top: 28px; padding-top: 20px; border-top: 2px solid #6b8f71; }
    .ai-section h2 { font-size: 16px; color: #3d5e42; margin-bottom: 10px; }
    .ai-note { font-size: 12px; color: #6b7280; margin-bottom: 12px; font-style: italic; }
    .ai-body { font-size: 13px; line-height: 1.8; color: #2d2d2d; }
    footer { margin-top: 36px; padding-top: 14px; border-top: 1px solid #dde8dd; font-size: 10.5px; color: #9ca3af; line-height: 1.6; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <header>
    <div>
      <h1>🌿 CelerySync — Healing Protocol Summary</h1>
      <p style="font-size:12px;color:#6b7280;margin-top:4px;">Based on Anthony William's Medical Medium teachings</p>
    </div>
    <div class="meta">
      <strong>Date:</strong> ${now}<br>
      <strong>Patient:</strong> ${user?.name || "—"}<br>
      <strong>Prepared by:</strong> CelerySync App
    </div>
  </header>

  <div class="patient-box">
    <h2>Patient Information</h2>
    <p>
      <strong>Name:</strong> ${user?.name || "—"} &nbsp;&nbsp;
      <strong>Healing Goal:</strong> ${user?.goal || "—"}<br>
      <strong>Conditions Selected:</strong> ${conditions.join(", ")}
    </p>
  </div>

  <h2 style="font-size:16px;color:#3d5e42;margin-bottom:16px;">Condition Protocols</h2>
  ${rows}
  ${aiSection}

  <footer>
    ⚠️ <strong>Important Notice for Healthcare Providers:</strong> This document summarises information paraphrased from Anthony William's publicly shared Medical Medium teachings. These are <em>complementary</em> wellness suggestions, not a replacement for medical diagnosis or treatment. Anthony William is not a licensed medical professional. All supplement use should be discussed with the patient's treating physician, particularly where medications or existing conditions may interact. For complete protocols and specific amounts, refer to Anthony William's books and medicalmedium.com.
  </footer>
</body>
</html>`;

  const win = window.open("", "_blank");
  win.document.write(html);
  win.document.close();
  setTimeout(() => win.print(), 400);
}

export default function Symptom({ user, navQuery }) {
  const [sel, setSel] = useState([]);
  const [custom, setCustom] = useState("");
  const [conditionSearch, setConditionSearch] = useState("");
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [streaming, setStreaming] = useState(false);
  const [showDrNote, setShowDrNote] = useState(false);
  const { speak, speaking, stopSpeaking } = useVoice();

  useEffect(() => {
    if (!navQuery) return;
    const q = navQuery.trim();
    const match = Object.keys(CONDITIONS).find(k => k.toLowerCase() === q.toLowerCase());
    if (match) setSel([match]);
    else setCustom(q);
  }, [navQuery]);

  const analyse = async () => {
    if (!sel.length && !custom.trim()) return;
    setLoading(true);
    setResult(null);
    setStreaming(false);

    const all = [...sel, ...(custom.trim() ? [custom.trim()] : [])];

    const dbContext = all
      .map((s) => {
        const match = Object.entries(CONDITIONS).find(
          ([k]) =>
            k.toLowerCase().includes(s.toLowerCase()) ||
            s.toLowerCase().includes(k.toLowerCase())
        );
        if (match) {
          return `${match[0]}: Cause: ${match[1].cause} | Supplements: ${match[1].supps.join(", ")} | Avoid: ${match[1].avoid.join(", ")}`;
        }
        return "";
      })
      .filter(Boolean)
      .join("\n");

    const prompt = `You are a compassionate CelerySync companion helping an adult explore Anthony William's Medical Medium teachings.

Person: ${user?.name || "friend"}
Their conditions: ${(user?.symptoms || []).join(", ") || "not previously specified"}
Conditions/symptoms they're exploring now: ${all.join(", ")}

PARAPHRASED DATA (attributed to Anthony William's teachings):
${dbContext || "Draw from Anthony William's publicly shared Medical Medium teachings."}

Be warm and compassionate. Address them by name (${user?.name || "friend"}).
Frame everything as "Anthony William teaches…" or "According to Anthony William…" — not as your own medical claims.
For supplement amounts, say "Anthony William generally suggests…" and point to the specific book for full detail — never state yourself as the dosing authority.
This is not medical advice. Always encourage working with a licensed practitioner.

⚠️ IMPORTANT: NEVER diagnose or claim to treat, cure, or heal any condition. Use "understand", "support", and "track" framing throughout.

Provide these sections:

## 🦠 What Anthony William Associates This With
What he teaches is the likely underlying cause — pathogen (EBV, streptococcus, etc.) or toxic load (heavy metals, etc.). Attribute clearly and cite the relevant book.

## 🌿 Suggested Starting Point
Based on Anthony William's teachings — which cleanse or approach he generally recommends. Point to Cleanse to Heal for the full protocol.

## 💊 Supplement Guidance (see book for full detail)
General supplements Anthony William associates with this, paraphrased from his teachings. Note the relevant book. For precise amounts and protocols, refer to the book directly.

## 🍎 Supportive Foods
Foods Anthony William highlights for this condition — per his teachings. Include any general timing notes.

## 🚫 Foods to Reduce or Avoid
Key foods he says feed the pathogens involved — per his teachings.

## 📚 Recommended Reading
The most relevant Anthony William book for this situation.

## 💛 Encouragement
One warm paragraph acknowledging this person's commitment to their wellbeing.

End with: ⚠️ This is based on Anthony William's Medical Medium teachings, paraphrased and attributed. This is not medical advice — always work with your healthcare provider. See Anthony William's books for complete protocols and supplement specifics.`;

    try {
      const text = await callClaude({
        tier: 'standard',
        maxTokens: 2000,
        messages: [{ role: "user", content: prompt }],
      });
      setResult(text);
    } catch (err) {
      setResult(`Connection error: ${err.message}. Please check your API key and try again.`);
    }
    setLoading(false);
  };

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
      <h2 style={{ margin: 0, fontFamily: "Georgia,serif", fontSize: 22, color: C.charcoal }}>
        🔍 Symptom Checker
      </h2>

      <div
        style={{
          background: C.sageLight,
          border: `1px solid ${C.sage}40`,
          borderRadius: 12,
          padding: 10,
          fontSize: 12,
          color: C.sageDark,
        }}
      >
        📖 Paraphrased from Anthony William's publicly shared teachings — attributed to him. Not medical advice; always work with your healthcare provider. See his books in the <strong>Resources</strong> tab for full detail.
      </div>

      {/* Condition search + chips */}
      <div>
        <input
          value={conditionSearch}
          onChange={(e) => setConditionSearch(e.target.value)}
          placeholder={`Search ${Object.keys(CONDITIONS).length} conditions…`}
          style={{
            width: "100%", boxSizing: "border-box",
            padding: "9px 16px", borderRadius: 30,
            border: `1.5px solid ${C.border}`,
            fontFamily: "Georgia,serif", fontSize: 13,
            outline: "none", background: C.mist,
            marginBottom: 10,
          }}
        />
        {sel.length > 0 && (
          <div style={{ display: "flex", gap: 6, flexWrap: "wrap", marginBottom: 8 }}>
            {sel.map((s) => (
              <div
                key={s}
                onClick={() => { setSel((p) => p.filter((x) => x !== s)); setResult(null); }}
                style={{
                  padding: "5px 12px", borderRadius: 30, fontSize: 12,
                  fontFamily: "Georgia,serif", cursor: "pointer",
                  border: `2px solid ${C.plum}`,
                  background: C.plumLight, color: C.plum, fontWeight: 700,
                }}
              >
                {s} ✕
              </div>
            ))}
          </div>
        )}
        <div style={{ display: "flex", flexWrap: "wrap", gap: 7, maxHeight: conditionSearch ? "none" : 180, overflowY: conditionSearch ? "visible" : "auto" }}>
          {Object.keys(CONDITIONS)
            .filter((s) => !conditionSearch || s.toLowerCase().includes(conditionSearch.toLowerCase()))
            .map((s) => (
              <div
                key={s}
                onClick={() => {
                  setSel((p) => (p.includes(s) ? p.filter((x) => x !== s) : [...p, s]));
                  setResult(null);
                }}
                style={{
                  padding: "7px 14px",
                  borderRadius: 30,
                  fontSize: 12,
                  fontFamily: "Georgia,serif",
                  cursor: "pointer",
                  border: `2px solid ${sel.includes(s) ? C.plum : C.border}`,
                  background: sel.includes(s) ? C.plumLight : "transparent",
                  color: sel.includes(s) ? C.plum : C.mid,
                  fontWeight: sel.includes(s) ? 700 : 400,
                }}
              >
                {s}
              </div>
            ))}
        </div>
        {!conditionSearch && (
          <div style={{ fontSize: 11, color: C.muted, marginTop: 6, textAlign: "center" }}>
            Showing all {Object.keys(CONDITIONS).length} conditions — search to filter
          </div>
        )}
      </div>

      <input
        value={custom}
        onChange={(e) => setCustom(e.target.value)}
        placeholder="Type another symptom…"
        style={{
          padding: "10px 16px",
          borderRadius: 30,
          border: `1.5px solid ${C.border}`,
          fontFamily: "Georgia,serif",
          fontSize: 14,
          outline: "none",
          background: C.mist,
        }}
      />

      <Btn
        full
        onClick={analyse}
        disabled={loading || (!sel.length && !custom.trim())}
        color={C.plum}
      >
        {loading ? "🌿 Looking it up…" : "Explore This Symptom"}
      </Btn>

      {result !== null && (
        <Card style={{ background: C.mist }}>
          <div
            style={{
              display: "flex",
              justifyContent: "space-between",
              alignItems: "center",
              marginBottom: 10,
              flexWrap: "wrap",
              gap: 8,
            }}
          >
            <div style={{ display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" }}>
              <div style={{ fontFamily: "Georgia,serif", fontWeight: 700, fontSize: 14, color: C.charcoal }}>
                Protocol Overview
              </div>
            </div>
            <div style={{ display: "flex", gap: 7, flexWrap: "wrap" }}>
              <Btn
                small
                onClick={() => (speaking ? stopSpeaking() : speak(result))}
                color={C.sage}
              >
                {speaking ? "⏹ Stop" : "🔊 Listen"}
              </Btn>
              <Btn
                small
                onClick={() => setShowDrNote((v) => !v)}
                color={C.plum}
              >
                🩺 Doctor Summary
              </Btn>
            </div>
          </div>

          {showDrNote && (
            <div style={{
              background: "#f0f7f0",
              border: `1px solid ${C.sage}50`,
              borderRadius: 12,
              padding: "14px 16px",
              marginBottom: 12,
            }}>
              <div style={{ fontFamily: "Georgia,serif", fontWeight: 700, fontSize: 13, color: C.sageDark, marginBottom: 8 }}>
                🩺 Doctor / Practitioner Summary
              </div>
              <div style={{ fontSize: 12.5, color: C.mid, lineHeight: 1.6, marginBottom: 12 }}>
                Creates a professional, printable protocol sheet with supplement dosages, foods to avoid, and book references — perfect to take to your GP, naturopath, or specialist.
              </div>
              <Btn
                full
                color={C.sageDark}
                onClick={() =>
                  printDoctorSummary({ user, conditions: sel, result })
                }
              >
                🖨 Print / Save as PDF
              </Btn>
            </div>
          )}

          <div
            style={{
              fontSize: 13.5,
              color: C.charcoal,
              lineHeight: 1.8,
              whiteSpace: "pre-wrap",
            }}
          >
            {result}
            {streaming && <span className="cs-cursor">▋</span>}
          </div>
        </Card>
      )}
    </div>
  );
}
