import { useState, useEffect } from "react";
import C from "../lib/colors.js";
import { useVoice } from "../hooks/useVoice.js";
import { Card, Btn } from "./ui.jsx";
import { CONDITIONS } from "../data/conditions.js";
import { callClaude } from "../lib/api.js";

function printDoctorSummary({ user, conditions, result }) {
  const now = new Date().toLocaleDateString("en-AU", {
    day: "numeric", month: "long", year: "numeric",
  });

  const rows = conditions.map((name) => {
    const c = CONDITIONS[name];
    if (!c) return "";
    return `
      <div class="condition-block">
        <h3>${name}</h3>
        <p class="cause"><strong>True Cause (per Anthony William):</strong> ${c.cause}</p>
        <table>
          <tr>
            <td class="col-head">Recommended Supplements</td>
            <td class="col-head">Foods to Avoid</td>
          </tr>
          <tr>
            <td><ul>${c.supps.map((s) => `<li>${s}</li>`).join("")}</ul></td>
            <td><ul>${c.avoid.map((a) => `<li>${a}</li>`).join("")}</ul></td>
          </tr>
        </table>
        ${c.book ? `<p class="book-ref">📚 Reference: <em>${c.book}</em> by Anthony William</p>` : ""}
      </div>`;
  }).join("");

  const aiSection = result ? `
    <div class="ai-section">
      <h2>AI-Generated Healing Protocol</h2>
      <p class="ai-note">The following was generated by the CelerySync AI Guide based on Anthony William's Medical Medium teachings:</p>
      <div class="ai-body">${result.replace(/\n/g, "<br>")}</div>
    </div>` : "";

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>CelerySync — Healing Protocol for ${user?.name || "Patient"}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: Georgia, serif; color: #1a1a1a; padding: 36px; max-width: 780px; margin: 0 auto; }
    header { border-bottom: 2px solid #6b8f71; padding-bottom: 16px; margin-bottom: 24px; display: flex; justify-content: space-between; align-items: flex-end; }
    header h1 { font-size: 22px; color: #3d5e42; }
    header .meta { font-size: 12px; color: #555; text-align: right; line-height: 1.6; }
    .patient-box { background: #f5f9f5; border: 1px solid #c8deca; border-radius: 8px; padding: 14px 18px; margin-bottom: 22px; font-size: 13px; }
    .patient-box h2 { font-size: 14px; color: #3d5e42; margin-bottom: 8px; }
    .patient-box p { line-height: 2; }
    .condition-block { margin-bottom: 28px; padding-bottom: 20px; border-bottom: 1px solid #e0e8e0; }
    .condition-block h3 { font-size: 17px; color: #3d5e42; margin-bottom: 8px; }
    .cause { font-size: 12.5px; color: #444; line-height: 1.6; margin-bottom: 10px; }
    table { width: 100%; border-collapse: collapse; font-size: 12px; }
    .col-head { background: #e8f0e8; font-weight: 700; padding: 7px 10px; font-size: 12px; color: #3d5e42; }
    td { padding: 6px 10px; vertical-align: top; border: 1px solid #dde8dd; }
    ul { padding-left: 16px; }
    li { margin-bottom: 3px; line-height: 1.5; }
    .book-ref { font-size: 11.5px; color: #6b7280; margin-top: 8px; font-style: italic; }
    .ai-section { margin-top: 28px; padding-top: 20px; border-top: 2px solid #6b8f71; }
    .ai-section h2 { font-size: 16px; color: #3d5e42; margin-bottom: 10px; }
    .ai-note { font-size: 12px; color: #6b7280; margin-bottom: 12px; font-style: italic; }
    .ai-body { font-size: 13px; line-height: 1.8; color: #2d2d2d; }
    footer { margin-top: 36px; padding-top: 14px; border-top: 1px solid #dde8dd; font-size: 10.5px; color: #9ca3af; line-height: 1.6; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <header>
    <div>
      <h1>🌿 CelerySync — Healing Protocol Summary</h1>
      <p style="font-size:12px;color:#6b7280;margin-top:4px;">Based on Anthony William's Medical Medium teachings</p>
    </div>
    <div class="meta">
      <strong>Date:</strong> ${now}<br>
      <strong>Patient:</strong> ${user?.name || "—"}<br>
      <strong>Prepared by:</strong> CelerySync App
    </div>
  </header>

  <div class="patient-box">
    <h2>Patient Information</h2>
    <p>
      <strong>Name:</strong> ${user?.name || "—"} &nbsp;&nbsp;
      <strong>Healing Goal:</strong> ${user?.goal || "—"}<br>
      <strong>Conditions Selected:</strong> ${conditions.join(", ")}
    </p>
  </div>

  <h2 style="font-size:16px;color:#3d5e42;margin-bottom:16px;">Condition Protocols</h2>
  ${rows}
  ${aiSection}

  <footer>
    ⚠️ <strong>Important Notice for Healthcare Providers:</strong> This document summarises protocols from Anthony William's Medical Medium book series. These are <em>complementary</em> wellness recommendations, not a replacement for medical diagnosis or treatment. Anthony William is not a licensed medical professional. All supplement use should be discussed with the patient's treating physician, particularly where medications or existing conditions may interact. The information is drawn from: <em>Medical Medium</em>, <em>Thyroid Healing</em>, <em>Liver Rescue</em>, <em>Cleanse to Heal</em>, and <em>Brain Saver</em> by Anthony William.
  </footer>
</body>
</html>`;

  const win = window.open("", "_blank");
  win.document.write(html);
  win.document.close();
  setTimeout(() => win.print(), 400);
}

export default function Symptom({ user, bookNotes, searchBooks, navQuery }) {
  const [sel, setSel] = useState([]);
  const [custom, setCustom] = useState("");
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [showDrNote, setShowDrNote] = useState(false);
  const [bookEnhanced, setBookEnhanced] = useState(false);
  const { speak, speaking, stopSpeaking } = useVoice();

  useEffect(() => {
    if (!navQuery) return;
    const q = navQuery.trim();
    const match = Object.keys(CONDITIONS).find(k => k.toLowerCase() === q.toLowerCase());
    if (match) setSel([match]);
    else setCustom(q);
  }, [navQuery]);

  const analyse = async () => {
    if (!sel.length && !custom.trim()) return;
    setLoading(true);
    setResult(null);
    setBookEnhanced(false);

    const all = [...sel, ...(custom.trim() ? [custom.trim()] : [])];

    const dbContext = all
      .map((s) => {
        const match = Object.entries(CONDITIONS).find(
          ([k]) =>
            k.toLowerCase().includes(s.toLowerCase()) ||
            s.toLowerCase().includes(k.toLowerCase())
        );
        if (match) {
          return `${match[0]}: Cause: ${match[1].cause} | Supplements: ${match[1].supps.join(", ")} | Avoid: ${match[1].avoid.join(", ")}`;
        }
        return "";
      })
      .filter(Boolean)
      .join("\n");

    const notesCtx =
      bookNotes.length > 0
        ? `\nUser's personal book notes: ${bookNotes
            .slice(0, 3)
            .map((n) => n.content)
            .join("; ")}`
        : "";

    // Search uploaded books for relevant passages
    let bookChunksCtx = "";
    if (searchBooks) {
      const chunks = await searchBooks(all.join(" ")).catch(() => []);
      if (chunks?.length > 0) {
        bookChunksCtx = `\n\nFROM USER'S UPLOADED BOOKS:\n${chunks.slice(0, 3).map((c) => `[${c.user_books?.title || "Their library"}]: ${c.content}`).join("\n\n")}`;
        setBookEnhanced(true);
      }
    }

    try {
      const text = await callClaude({
        maxTokens: 1000,
        messages: [
          {
            role: "user",
            content: `You are a Medical Medium healing companion with exact data from Anthony William's books.

User symptoms: ${all.join(", ")}

EXACT DATA FROM ANTHONY WILLIAM'S BOOKS:
${dbContext || "Use Anthony William's Medical Medium teachings."}
${notesCtx}${bookChunksCtx}

Provide a response with these sections:
1. 🦠 TRUE CAUSE (attribute clearly to Anthony William and cite which book/chapter)
2. 🌿 BEST CLEANSE to start (from Cleanse to Heal by Anthony William)
3. 💊 EXACT SUPPLEMENTS with dosages (as taught by Anthony William)
4. 🍎 HEALING FOODS to eat daily (per Anthony William)
5. 🚫 AVOID these foods (per Anthony William's teachings)
6. 📚 Which Anthony William book to read next
7. 💛 Encouragement

Important: Always frame causes and protocols as Anthony William's teachings, not as your own claims. Use phrases like "Anthony William teaches…", "According to Anthony William…", "Per Cleanse to Heal…".

End with: ⚠️ Based on Anthony William's Medical Medium teachings. Always consult your healthcare provider.`,
          },
        ],
      });
      setResult(text);
    } catch (err) {
      setResult(`Connection error: ${err.message}. Please check your API key in .env and try again.`);
    }
    setLoading(false);
  };

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
      <h2 style={{ margin: 0, fontFamily: "Georgia,serif", fontSize: 22, color: C.charcoal }}>
        🔍 Symptom Checker
      </h2>

      <div
        style={{
          background: C.sageLight,
          border: `1px solid ${C.sage}40`,
          borderRadius: 12,
          padding: 10,
          fontSize: 12,
          color: C.sageDark,
        }}
      >
        📚 Powered by exact data from <strong>Cleanse to Heal Ch. 29</strong> by Anthony William
      </div>

      {/* Symptom chips */}
      <div style={{ display: "flex", flexWrap: "wrap", gap: 7 }}>
        {Object.keys(CONDITIONS).map((s) => (
          <div
            key={s}
            onClick={() => {
              setSel((p) => (p.includes(s) ? p.filter((x) => x !== s) : [...p, s]));
              setResult(null);
            }}
            style={{
              padding: "7px 14px",
              borderRadius: 30,
              fontSize: 12,
              fontFamily: "Georgia,serif",
              cursor: "pointer",
              border: `2px solid ${sel.includes(s) ? C.plum : C.border}`,
              background: sel.includes(s) ? C.plumLight : "transparent",
              color: sel.includes(s) ? C.plum : C.mid,
              fontWeight: sel.includes(s) ? 700 : 400,
            }}
          >
            {s}
          </div>
        ))}
      </div>

      <input
        value={custom}
        onChange={(e) => setCustom(e.target.value)}
        placeholder="Type another symptom…"
        style={{
          padding: "10px 16px",
          borderRadius: 30,
          border: `1.5px solid ${C.border}`,
          fontFamily: "Georgia,serif",
          fontSize: 14,
          outline: "none",
          background: C.mist,
        }}
      />

      <Btn
        full
        onClick={analyse}
        disabled={loading || (!sel.length && !custom.trim())}
        color={C.plum}
      >
        {loading ? "🌿 Looking it up…" : "Understand & Heal This Symptom"}
      </Btn>

      {result && (
        <Card style={{ background: C.mist }}>
          <div
            style={{
              display: "flex",
              justifyContent: "space-between",
              alignItems: "center",
              marginBottom: 10,
              flexWrap: "wrap",
              gap: 8,
            }}
          >
            <div style={{ display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" }}>
              <div style={{ fontFamily: "Georgia,serif", fontWeight: 700, fontSize: 14, color: C.charcoal }}>
                Your Healing Protocol
              </div>
              {bookEnhanced && (
                <span style={{
                  fontSize: 10, fontWeight: 700,
                  padding: "2px 9px", borderRadius: 20,
                  background: "#e8f5e9", color: C.sageDark,
                  border: `1px solid ${C.sage}50`,
                }}>
                  📚 Enhanced by your library
                </span>
              )}
            </div>
            <div style={{ display: "flex", gap: 7, flexWrap: "wrap" }}>
              <Btn
                small
                onClick={() => (speaking ? stopSpeaking() : speak(result))}
                color={C.sage}
              >
                {speaking ? "⏹ Stop" : "🔊 Listen"}
              </Btn>
              <Btn
                small
                onClick={() => setShowDrNote((v) => !v)}
                color={C.plum}
              >
                🩺 Doctor Summary
              </Btn>
            </div>
          </div>

          {showDrNote && (
            <div style={{
              background: "#f0f7f0",
              border: `1px solid ${C.sage}50`,
              borderRadius: 12,
              padding: "14px 16px",
              marginBottom: 12,
            }}>
              <div style={{ fontFamily: "Georgia,serif", fontWeight: 700, fontSize: 13, color: C.sageDark, marginBottom: 8 }}>
                🩺 Doctor / Practitioner Summary
              </div>
              <div style={{ fontSize: 12.5, color: C.mid, lineHeight: 1.6, marginBottom: 12 }}>
                Creates a professional, printable protocol sheet with supplement dosages, foods to avoid, and book references — perfect to take to your GP, naturopath, or specialist.
              </div>
              <Btn
                full
                color={C.sageDark}
                onClick={() =>
                  printDoctorSummary({ user, conditions: sel, result })
                }
              >
                🖨 Print / Save as PDF
              </Btn>
            </div>
          )}

          <div
            style={{
              fontSize: 13.5,
              color: C.charcoal,
              lineHeight: 1.8,
              whiteSpace: "pre-wrap",
            }}
          >
            {result}
          </div>
        </Card>
      )}
    </div>
  );
}
